version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: PASSWORD
      MYSQL_DATABASE: charity
    restart: always
    ports:
      - '3305:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
