import {
  PERMISSIONS,
  ROLE_IDS,
  type RoleSeed,
  type PermissionAction
} from './seed.types';

export const rolesData: RoleSeed[] = [
  {
    id: ROLE_IDS.SUPER_ADMIN,
    name: 'Super Admin',
    scope: 'ORGANIZATION',
    organization_id: 1
  },
  {
    id: ROLE_IDS.BRANCH_MANAGER,
    name: 'Branch Manager',
    scope: 'BRANCH',
    organization_id: 1
  },
  {
    id: ROLE_IDS.STAFF,
    name: 'Staff',
    scope: 'BRANCH',
    organization_id: 1
  },
  {
    id: ROLE_IDS.VOLUNTEER,
    name: 'Volunteer',
    scope: 'BRANCH',
    organization_id: 1
  }
];

// Type-safe permission arrays
export const rolePermissions: Record<
  keyof typeof ROLE_IDS,
  PermissionAction[]
> = {
  SUPER_ADMIN: [
    PERMISSIONS.USER_CREATE,
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.USER_DELETE,
    PERMISSIONS.USER_LIST,

    PERMISSIONS.ORGANIZATION_CREATE,
    PERMISSIONS.ORGANIZATION_READ,
    PERMISSIONS.ORGANIZATION_UPDATE,
    PERMISSIONS.ORGANIZATION_DELETE,
    PERMISSIONS.ORGANIZATION_LIST,

    PERMISSIONS.BRANCH_CREATE,
    PERMISSIONS.BRANCH_READ,
    PERMISSIONS.BRANCH_UPDATE,
    PERMISSIONS.BRANCH_DELETE,
    PERMISSIONS.BRANCH_LIST,

    PERMISSIONS.BENEFICIARY_CREATE,
    PERMISSIONS.BENEFICIARY_READ,
    PERMISSIONS.BENEFICIARY_UPDATE,
    PERMISSIONS.BENEFICIARY_DELETE,
    PERMISSIONS.BENEFICIARY_LIST,

    PERMISSIONS.BENEFIT_CREATE,
    PERMISSIONS.BENEFIT_READ,
    PERMISSIONS.BENEFIT_UPDATE,
    PERMISSIONS.BENEFIT_DELETE,
    PERMISSIONS.BENEFIT_LIST,

    PERMISSIONS.FINANCIAL_BENEFIT_CREATE,
    PERMISSIONS.FINANCIAL_BENEFIT_READ,
    PERMISSIONS.FINANCIAL_BENEFIT_UPDATE,
    PERMISSIONS.FINANCIAL_BENEFIT_DELETE,
    PERMISSIONS.FINANCIAL_BENEFIT_LIST,

    PERMISSIONS.ITEM_CREATE,
    PERMISSIONS.ITEM_READ,
    PERMISSIONS.ITEM_UPDATE,
    PERMISSIONS.ITEM_DELETE,
    PERMISSIONS.ITEM_LIST,
    PERMISSIONS.ITEM_SEARCH_BY_NAME,

    PERMISSIONS.CATEGORY_CREATE,
    PERMISSIONS.CATEGORY_READ,
    PERMISSIONS.CATEGORY_UPDATE,
    PERMISSIONS.CATEGORY_DELETE,
    PERMISSIONS.CATEGORY_LIST,

    PERMISSIONS.UNIT_CREATE,
    PERMISSIONS.UNIT_READ,
    PERMISSIONS.UNIT_UPDATE,
    PERMISSIONS.UNIT_DELETE,
    PERMISSIONS.UNIT_LIST,

    PERMISSIONS.DONATE_CREATE,
    PERMISSIONS.DONATE_READ,
    PERMISSIONS.DONATE_UPDATE,
    PERMISSIONS.DONATE_DELETE,
    PERMISSIONS.DONATE_LIST,

    PERMISSIONS.TRANSACTION_CREATE,
    PERMISSIONS.TRANSACTION_READ,
    PERMISSIONS.TRANSACTION_UPDATE,
    PERMISSIONS.TRANSACTION_DELETE,
    PERMISSIONS.TRANSACTION_LIST,

    PERMISSIONS.NOTE_CREATE,
    PERMISSIONS.NOTE_READ,
    PERMISSIONS.NOTE_UPDATE,
    PERMISSIONS.NOTE_DELETE,
    PERMISSIONS.NOTE_LIST,
    PERMISSIONS.NOTE_READ_PRIVATE,
    PERMISSIONS.NOTE_READ_PUBLIC,

    PERMISSIONS.VISIT_CREATE,
    PERMISSIONS.VISIT_READ,
    PERMISSIONS.VISIT_UPDATE,
    PERMISSIONS.VISIT_DELETE,
    PERMISSIONS.VISIT_LIST,

    PERMISSIONS.SETUP_READ,
    PERMISSIONS.SETUP_UPDATE,

    PERMISSIONS.ROLE_CREATE,
    PERMISSIONS.ROLE_READ,
    PERMISSIONS.ROLE_UPDATE,
    PERMISSIONS.ROLE_DELETE,
    PERMISSIONS.ROLE_LIST,
    PERMISSIONS.ROLE_ASSIGN,

    PERMISSIONS.PERMISSION_READ,
    PERMISSIONS.PERMISSION_LIST,

    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_GENERATE
  ],

  BRANCH_MANAGER: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_LIST,

    PERMISSIONS.BRANCH_READ,
    PERMISSIONS.BRANCH_UPDATE,

    PERMISSIONS.BENEFICIARY_CREATE,
    PERMISSIONS.BENEFICIARY_READ,
    PERMISSIONS.BENEFICIARY_UPDATE,
    PERMISSIONS.BENEFICIARY_DELETE,
    PERMISSIONS.BENEFICIARY_LIST,

    PERMISSIONS.BENEFIT_CREATE,
    PERMISSIONS.BENEFIT_READ,
    PERMISSIONS.BENEFIT_UPDATE,
    PERMISSIONS.BENEFIT_DELETE,
    PERMISSIONS.BENEFIT_LIST,

    PERMISSIONS.FINANCIAL_BENEFIT_CREATE,
    PERMISSIONS.FINANCIAL_BENEFIT_READ,
    PERMISSIONS.FINANCIAL_BENEFIT_UPDATE,
    PERMISSIONS.FINANCIAL_BENEFIT_DELETE,
    PERMISSIONS.FINANCIAL_BENEFIT_LIST,

    PERMISSIONS.ITEM_CREATE,
    PERMISSIONS.ITEM_READ,
    PERMISSIONS.ITEM_UPDATE,
    PERMISSIONS.ITEM_DELETE,
    PERMISSIONS.ITEM_LIST,
    PERMISSIONS.ITEM_SEARCH_BY_NAME,

    PERMISSIONS.CATEGORY_CREATE,
    PERMISSIONS.CATEGORY_READ,
    PERMISSIONS.CATEGORY_UPDATE,
    PERMISSIONS.CATEGORY_DELETE,
    PERMISSIONS.CATEGORY_LIST,

    PERMISSIONS.UNIT_CREATE,
    PERMISSIONS.UNIT_READ,
    PERMISSIONS.UNIT_UPDATE,
    PERMISSIONS.UNIT_DELETE,
    PERMISSIONS.UNIT_LIST,

    PERMISSIONS.DONATE_CREATE,
    PERMISSIONS.DONATE_READ,
    PERMISSIONS.DONATE_UPDATE,
    PERMISSIONS.DONATE_DELETE,
    PERMISSIONS.DONATE_LIST,

    PERMISSIONS.TRANSACTION_CREATE,
    PERMISSIONS.TRANSACTION_READ,
    PERMISSIONS.TRANSACTION_UPDATE,
    PERMISSIONS.TRANSACTION_DELETE,
    PERMISSIONS.TRANSACTION_LIST,

    PERMISSIONS.NOTE_CREATE,
    PERMISSIONS.NOTE_READ,
    PERMISSIONS.NOTE_UPDATE,
    PERMISSIONS.NOTE_DELETE,
    PERMISSIONS.NOTE_LIST,
    PERMISSIONS.NOTE_READ_PRIVATE,
    PERMISSIONS.NOTE_READ_PUBLIC,

    PERMISSIONS.VISIT_CREATE,
    PERMISSIONS.VISIT_READ,
    PERMISSIONS.VISIT_UPDATE,
    PERMISSIONS.VISIT_DELETE,
    PERMISSIONS.VISIT_LIST,

    PERMISSIONS.SETUP_READ,
    PERMISSIONS.SETUP_UPDATE,

    PERMISSIONS.ROLE_READ,
    PERMISSIONS.ROLE_LIST,
    PERMISSIONS.ROLE_ASSIGN,

    PERMISSIONS.PERMISSION_READ,
    PERMISSIONS.PERMISSION_LIST,

    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,
    PERMISSIONS.REPORT_GENERATE
  ],

  STAFF: [
    PERMISSIONS.BENEFICIARY_CREATE,
    PERMISSIONS.BENEFICIARY_READ,
    PERMISSIONS.BENEFICIARY_UPDATE,
    PERMISSIONS.BENEFICIARY_LIST,

    PERMISSIONS.BENEFIT_CREATE,
    PERMISSIONS.BENEFIT_READ,
    PERMISSIONS.BENEFIT_UPDATE,
    PERMISSIONS.BENEFIT_LIST,

    PERMISSIONS.FINANCIAL_BENEFIT_CREATE,
    PERMISSIONS.FINANCIAL_BENEFIT_READ,
    PERMISSIONS.FINANCIAL_BENEFIT_UPDATE,
    PERMISSIONS.FINANCIAL_BENEFIT_LIST,

    PERMISSIONS.ITEM_READ,
    PERMISSIONS.ITEM_LIST,
    PERMISSIONS.ITEM_SEARCH_BY_NAME,

    PERMISSIONS.CATEGORY_READ,
    PERMISSIONS.CATEGORY_LIST,

    PERMISSIONS.UNIT_READ,
    PERMISSIONS.UNIT_LIST,

    PERMISSIONS.DONATE_CREATE,
    PERMISSIONS.DONATE_READ,
    PERMISSIONS.DONATE_LIST,

    PERMISSIONS.TRANSACTION_CREATE,
    PERMISSIONS.TRANSACTION_READ,
    PERMISSIONS.TRANSACTION_LIST,

    PERMISSIONS.NOTE_CREATE,
    PERMISSIONS.NOTE_READ,
    PERMISSIONS.NOTE_LIST,
    PERMISSIONS.NOTE_READ_PRIVATE,
    PERMISSIONS.NOTE_READ_PUBLIC,

    PERMISSIONS.VISIT_CREATE,
    PERMISSIONS.VISIT_READ,
    PERMISSIONS.VISIT_UPDATE,
    PERMISSIONS.VISIT_LIST,

    PERMISSIONS.REPORT_VIEW
  ],

  VOLUNTEER: [
    PERMISSIONS.BENEFICIARY_READ,
    PERMISSIONS.BENEFICIARY_LIST,

    PERMISSIONS.BENEFIT_READ,
    PERMISSIONS.BENEFIT_LIST,

    PERMISSIONS.FINANCIAL_BENEFIT_READ,
    PERMISSIONS.FINANCIAL_BENEFIT_LIST,

    PERMISSIONS.ITEM_READ,
    PERMISSIONS.ITEM_LIST,
    PERMISSIONS.ITEM_SEARCH_BY_NAME,

    PERMISSIONS.CATEGORY_READ,
    PERMISSIONS.CATEGORY_LIST,

    PERMISSIONS.UNIT_READ,
    PERMISSIONS.UNIT_LIST,

    PERMISSIONS.DONATE_READ,
    PERMISSIONS.DONATE_LIST,

    PERMISSIONS.TRANSACTION_READ,
    PERMISSIONS.TRANSACTION_LIST,

    PERMISSIONS.NOTE_READ,
    PERMISSIONS.NOTE_LIST,
    PERMISSIONS.NOTE_READ_PUBLIC,

    PERMISSIONS.VISIT_READ,
    PERMISSIONS.VISIT_LIST
  ]
};
