export const moneyUnits = [
  {
    en_code: "USD",
    en_name: "US Dollar",
    ar_code: "د.أ",
    ar_name: "دولار امريكي",
  },
  { en_code: "EUR", en_name: "Euro", ar_code: "ي.أ", ar_name: "يورو" },
  {
    en_code: "EGP",
    en_name: "Egyptian Pound",
    ar_code: "ج.م",
    ar_name: "جنيه مصري",
  },
  {
    en_code: "GBP",
    en_name: "British Pound",
    ar_code: "ج.إ",
    ar_name: "جنيه إسترليني",
  },
  {
    en_code: "JPY",
    en_name: "Japanese Yen",
    ar_code: "ي.ي",
    ar_name: "ين ياباني",
  },
  {
    en_code: "CNY",
    en_name: "Chinese Yuan",
    ar_code: "ي.ص",
    ar_name: "يوان صيني",
  },
  {
    en_code: "SAR",
    en_name: "Saudi Riyal",
    ar_code: "ر.س",
    ar_name: "ريال سعودي",
  },
  {
    en_code: "AED",
    en_name: "UAE Dirham",
    ar_code: "د.إ",
    ar_name: "درهم إماراتي",
  },
  {
    en_code: "TRY",
    en_name: "Turkish Lira",
    ar_code: "ل.ت",
    ar_name: "ليرة تركية",
  },
  {
    en_code: "INR",
    en_name: "Indian Rupee",
    ar_code: "ر.ه",
    ar_name: "روبية هندية",
  },
  {
    en_code: "AUD",
    en_name: "Australian Dollar",
    ar_code: "د.أ",
    ar_name: "دولار أسترالي",
  },
  {
    en_code: "CAD",
    en_name: "Canadian Dollar",
    ar_code: "د.ك",
    ar_name: "دولار كندي",
  },
  {
    en_code: "CHF",
    en_name: "Swiss Franc",
    ar_code: "ف.س",
    ar_name: "فرنك سويسري",
  },
  {
    en_code: "BRL",
    en_name: "Brazilian Real",
    ar_code: "ر.ب",
    ar_name: "ريال برازيلي",
  },
  {
    en_code: "ZAR",
    en_name: "South African Rand",
    ar_code: "ر.ج",
    ar_name: "راند جنوب أفريقي",
  },
  {
    en_code: "KWD",
    en_name: "Kuwaiti Dinar",
    ar_code: "د.ك",
    ar_name: "دينار كويتي",
  },
  {
    en_code: "OMR",
    en_name: "Omani Rial",
    ar_code: "ر.ع",
    ar_name: "ريال عماني",
  },
  {
    en_code: "JOD",
    en_name: "Jordanian Dinar",
    ar_code: "د.أ",
    ar_name: "دينار أردني",
  },
  {
    en_code: "TND",
    en_name: "Tunisian Dinar",
    ar_code: "د.ت",
    ar_name: "دينار تونسي",
  },
  {
    en_code: "MAD",
    en_name: "Moroccan Dirham",
    ar_code: "د.م",
    ar_name: "درهم مغربي",
  },
  {
    en_code: "LYD",
    en_name: "Libyan Dinar",
    ar_code: "د.ل",
    ar_name: "دينار ليبي",
  },
  {
    en_code: "LBP",
    en_name: "Lebanese Pound",
    ar_code: "ل.ل",
    ar_name: "ليرة لبنانية",
  },
  {
    en_code: "SYP",
    en_name: "Syrian Pound",
    ar_code: "ل.س",
    ar_name: "ليرة سورية",
  },
  {
    en_code: "IQD",
    en_name: "Iraqi Dinar",
    ar_code: "د.ع",
    ar_name: "دينار عراقي",
  },
  {
    en_code: "YER",
    en_name: "Yemeni Rial",
    ar_code: "ر.ي",
    ar_name: "ريال يمني",
  },
  {
    en_code: "DZD",
    en_name: "Algerian Dinar",
    ar_code: "د.ج",
    ar_name: "دينار جزائري",
  },
  {
    en_code: "PAB",
    en_name: "Palestinian Pound",
    ar_code: "ج.ف",
    ar_name: "جنيه فلسطيني",
  },
  {
    en_code: "QAR",
    en_name: "Qatari Riyal",
    ar_code: "ر.ق",
    ar_name: "ريال قطري",
  },
  {
    en_code: "BHD",
    en_name: "Bahraini Dinar",
    ar_code: "د.ب",
    ar_name: "دينار بحريني",
  },
  {
    en_code: "SDG",
    en_name: "Sudanese Pound",
    ar_code: "ج.س",
    ar_name: "جنيه سوداني",
  },
];
